language: c++
compiler: gcc
sudo: true
matrix:
  include:
  # fully specify builds, include can't dynamically expand matrix entries
  # relative order of sudo and env is important so that addons: is recognized

# Linux 64bit, OF master
  - os: linux
    dist: trusty
    sudo: required
    env: TARGET="linux64" OF_BRANCH="master"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
          - g++-4.9
          - gdb

# OSX, OF master
  - os: osx
    # osx_image: xcode10.1
    compiler: clang
    env: TARGET="osx" OF_BRANCH="master"

  # Exclude the default build that would otherwise be generated
  # see https://github.com/travis-ci/travis-ci/issues/1228
  exclude:
    - compiler: gcc
before_install:
  - echo "BEFORE INSTALL================="
  - pwd
  # - curl -SLsO https://raw.githubusercontent.com/bakercp/ofxAddonScripts/${OF_BRANCH}/scripts/ci/tools/install.sh
  # - source install.sh
install:
  - echo "INSTALL ================="
  - scripts/./bootstrap.sh
  # - do_install
before_script:
script:
  - echo "SCRIPT ================="
  - pwd
  # - do_script
after_script:
  - echo "AFTER SCRIPT ================="
  - pwd

after_success:
  - echo "AFTER SUCCESS ================="
  - pwd

after_failure:
  - echo "AFTER FAILURE ================="
  - pwd


git:
  depth: 10
