language: c++
compiler: gcc
sudo: true
git:
  depth: 1
  quiet: true
matrix:
  include:
  # fully specify builds, include can't dynamically expand matrix entries
  # relative order of sudo and env is important so that addons: is recognized

# Linux 64bit, OF master
  - os: linux
    dist: trusty
    sudo: required
    env: TARGET="linux64" OF_BRANCH="master"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          # - doxygen
          - realpath
          - gcc-4.9
          - g++-4.9
          - gdb

# OSX, OF master
  - os: osx
    # osx_image: xcode10.1
    compiler: clang
    env: TARGET="osx" OF_BRANCH="master"
    # addons:
    #   homebrew:
    #     packages:
    #       - doxygen
    #     update: true
        
# before_install:
install:
  # - git clone --depth=1 --branch=master https://github.com/openFrameworks/openFrameworks.git ~/openFrameworks
  # - /usr/bin/env bash ~/openFrameworks/scripts/ci/addons/install.sh
  # - git clone https://github.com/bakercp/ofx.git ~/openFrameworks/scripts/ofx
script:
  # -  /usr/bin/env bash ~/openFrameworks/scripts/ofx/ofx ci script ${TRAVIS_REPO_SLUG#*/}
# after_script:
# after_success:
# after_failure:

jobs:
  include:
    - stage: deploy
      addons:
        apt:
          packages:
            - doxygen
      script: 
        - pwd 
        - ls -la
        - cd docs
        - doxygen Doxyfile
        - touch htom/.nojekyll
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: false
        local_dir: docs/html
        on:
          branch: master
  