language: c++
compiler: gcc
sudo: true
matrix:
  include:
  # fully specify builds, include can't dynamically expand matrix entries
  # relative order of sudo and env is important so that addons: is recognized

# Linux 64bit, OF master
  - os: linux
    dist: trusty
    sudo: required
    env: TARGET="linux64" OF_BRANCH="master"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
          - g++-4.9
          - gdb

# OSX, OF master
  - os: osx
    # osx_image: xcode10.1
    compiler: clang
    env: TARGET="osx" OF_BRANCH="master"

  # Exclude the default build that would otherwise be generated
  # see https://github.com/travis-ci/travis-ci/issues/1228
  exclude:
    - compiler: gcc
# before_install:
# install:
# - scripts/ofx/./ofx -v bootstrap
# before_script:
script:
  - scripts/ofx/./ofx -v ci
# after_script:
# after_success:
# after_failure:

git:
  depth: 10
